--- 
spring: 
  autoconfigure: 
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ""
    url: "jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true&serverTimeZone=UTC"
    username: root
  jpa: 
    hibernate: 
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
