--- 
spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    password: ""
    url: "jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true"
    username: root
  jpa: 
    hibernate: 
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

